### ISSUE TITLE
Review how to contribute

### ISSUE THREAD

**Issue by beraldoleal** [kytos/documentation#36]
We have to do a big review on how to contribute in order to fit our new dev model.

**Comment by diraol** [comment]
@beraldoleal this was for the previous milestone. Should it be rescheduled? Or it was done?

**Comment by beraldoleal** [comment]
I think that @cemsbr already did. But maybe we should take a second look.

**Comment by renanrodrigo** [comment]
@beraldoleal seems it can be closed, the docs page has everything working and is up to date.
