### ISSUE TITLE
Installing.rst needs a small syntax adjustment

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/documentation#47]
"Configuring" and "Installing" are formatted as two sections in the same file. Both appear at the top-left menu and are shown in the same page.

If "Configuring" is a subsection of "Installing", it's syntax has to be changed for that.

If "Configuring" is a new section, it should be moved to a new `.rst` file.

**Comment by beraldoleal** [comment]
@renanrodrigo Configuring is a new section and no I don't see reason to move it to a new .rst. Kytos Administrator Guide's  config section, should have a more detailed information about configuring.

Sorry, but what I'm missing ?

**Comment by renanrodrigo** [comment]
If the Administrator Guide has more information, I think this "Configuring" title could be a subsection pointing there.

"Installing" and "Configuring" are the only two sections that share the same page. Every other section in the left-side Menu has it's own page with subsections, so I think this could be inconsistent.

Besides that, "Configure" being a section shall appear in the footer of docs.kytos.io, again, to keep consistence.

**Comment by beraldoleal** [comment]
The last sentence is enough:

`For more information about the config options please visit the Kytos’s Administrator Guide.`

Talk with me on irc to explain me better.

**Comment by cemsbr** [comment]
@renanrodrigo, is this finished?

**Comment by cemsbr** [comment]
I'm closing this issue because we are changing the sections drastically.

**Comment by renanrodrigo** [comment]
@cemsbr No problem, we didn't decide what was the best approach anyway.
