### ISSUE TITLE
Footer of tutorials page is outdated

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/documentation#53]
https://tutorials.kytos.io has the correct footer, but inside the tutorials (like in https://tutorials.kytos.io/napps/development_environment_setup/ ) we can still see references to kyco and to old repositories.

**Comment by cemsbr** [comment]
@renanrodrigo, was this solved in the reviews?

**Comment by renanrodrigo** [comment]
@cemsbr no, it's still outdated.

**Comment by diraol** [comment]
It is a 'problem' with our sphinx template, it need to be updated on all sphinx 'projects' that we have.

**Comment by renanrodrigo** [comment]
Solved in bb8c38980c7be369711adcd28191694a577600cd

I'm closing this.
