### ISSUE TITLE
Create a L3 tutorial

### ISSUE THREAD

**Issue by diraol** [kytos/documentation#54]
@renanrodrigo if you can add some guidelines for this tutorial and its purpose I would appreciate!
Just two or three sentences on the issue is more than enough. =)

**Comment by renanrodrigo** [comment]
The idea is to create a series of tutorials on how to deploy an L3 switch, step by step.
Anyone following will end up with a simple pseudo-router implementation (which does almost all basic things a router does). We need to:

- [x] Switch packets matching the IP Addresses.
- [ ] Deal with ARP packets accordingly.
- [ ] Assign IP addresses to switch's interfaces using a REST API and GARP
- [ ] Answer ICMP requests
- [ ] Route between different IP networks
