### ISSUE TITLE
RRD dependency

### ISSUE THREAD

**Issue by diraol** [kytos/documentation#58]
We need to see if every time RRD is needed at our tutorials the RRD installation process is covered on the tutorial or on previous tutorials.

This applies for both the python rrd library (NApp python dependency) and also the system RRD tool.

**Comment by renanrodrigo** [comment]
Right now, only the `kytos/of_stats` NApp needs RRD. This NApp is used in the [RESTful Statistics NApp](https://github.com/kytos/documentation/blob/master/tutorials/napps/restful_statistics.rst) tutorial.
In the ['what will you need'](https://github.com/kytos/documentation/blob/master/tutorials/napps/restful_statistics.rst#what-you-will-need) section there is a reference for the installation of RRD as described in the very first tutorial, ['Setting up your dev environment'](https://github.com/kytos/documentation/blob/master/tutorials/napps/development_environment_setup.rst).

IMHO it's covered enough, but it would be sensible to move the instructions to the specific `of_stats` tutorial page.

**Comment by diraol** [comment]
Great then! [I didn't remember that!]

I think that for now we can just let RRD setup on the `of_stats` tutorial. Also keep the installation of the `kytos/of_stats` NApp just on that tutorial, since it is the only place where it is needed and also it requires some extra 'tunnings'.
