### ISSUE TITLE
Update install procedure

### ISSUE THREAD

**Issue by cemsbr** [kytos/documentation#66]
kytos, kytos-utils and python-openflow should use either one of the commands below to be installed:
- Devs: `pip install -r requirements/dev.txt`
- End-users with venv willing to use `git pull` to update Kytos: `pip install -r requirements/run.txt`

This way, we can all have the same versions of all dependencies and, thus, the same software behavior.

**Comment by cemsbr** [comment]
Issue is blocked until the projects update their dependencies accordingly.

**Comment by hdiogenes** [comment]
fixed
