### ISSUE TITLE
Invalid RESTful URL in tutorial

### ISSUE THREAD

**Issue by yjlcoder** [kytos/documentation#67]
I'm new to kytos and I'm following the tutorial, but there are some mismatchings.

I follow the every step of the tutorial, and in [RESTful Statistics NApp](https://tutorials.kytos.io/napps/restful_statistics/#rest-api), I could visit the [localhost:8181](http://localhost:8181), but can't visit [http://localhost:8181/kytos/stats/00:00:00:00:00:00:00:01/flows](http://localhost:8181/kytos/stats/00:00:00:00:00:00:00:01/flows) even after I enabled the kytos controller, mininet and every essential Napp.

**Comment by renanrodrigo** [comment]
Hello @LovingYoung , thanks for your feedback.
We have recently updated every endpoint, and tutorials are in queue for updating. We'll be working on that.
